// LGA boundary loader + point-in-polygon used by the public survey location
// gate. The boundary file (geo/nigeria_lgas.json) is generated by
// scripts/fetchNigeriaLgaBoundaries.js and is intentionally NOT committed to
// the repo (see AGENTS.md deploy notes). When the file is absent the gate
// falls back to the older Google-name check.
//
// File format:
//   { count, source, features: [ { s, lga, c: [rings] } ] }
// where c is an array of rings and each ring is an array of [lng, lat].

const fs = require('fs');
const path = require('path');

const DEFAULT_FILE = path.join(__dirname, '..', 'geo', 'nigeria_lgas.json');

let state = null;

const boundaryFile = () => process.env.SURVEY_BOUNDARY_FILE || DEFAULT_FILE;

// Aggressive key: case/space/punctuation-insensitive ("AbaNorth" === "Aba North",
// "FederalCapitalTerritory" === "Federal Capital Territory").
const normalizeKey = (value) => String(value || '').toLowerCase().replace(/[^a-z0-9]/g, '');

const stateKeyMatches = (a, b) => {
  const ka = normalizeKey(a);
  const kb = normalizeKey(b);
  if (!ka || !kb) return false;
  return (
    ka === kb ||
    ka.includes(kb) ||
    kb.includes(ka) ||
    ka === 'fct' ||
    kb === 'fct'
  );
};

const lgaKeyMatches = (a, b) => {
  const ka = normalizeKey(a);
  const kb = normalizeKey(b);
  return Boolean(ka) && Boolean(kb) && (ka === kb || ka.includes(kb) || kb.includes(ka));
};

function computeBBox(rings) {
  let minX = Infinity;
  let minY = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;
  for (const ring of rings) {
    for (const [x, y] of ring) {
      if (x < minX) minX = x;
      if (x > maxX) maxX = x;
      if (y < minY) minY = y;
      if (y > maxY) maxY = y;
    }
  }
  return [minX, minY, maxX, maxY];
}

// Even-odd rule across every ring; holes subtract automatically.
function pointInRings(rings, x, y) {
  let inside = false;
  for (const ring of rings) {
    for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
      const [xi, yi] = ring[i];
      const [xj, yj] = ring[j];
      const intersects =
        (yi > y) !== (yj > y) && x < ((xj - xi) * (y - yi)) / (yj - yi) + xi;
      if (intersects) inside = !inside;
    }
  }
  return inside;
}

const loadBoundaries = () => {
  if (state) return state;
  try {
    const data = JSON.parse(fs.readFileSync(boundaryFile(), 'utf8'));
    const features = (data.features || []).map((f) => ({
      s: f.s,
      lga: f.lga,
      c: f.c,
      bbox: computeBBox(f.c),
    }));
    state = { features, source: data.source || 'file', count: features.length };
  } catch (error) {
    state = { features: [], source: 'unavailable', count: 0, error: error.message };
  }
  return state;
};

const boundariesReady = () => loadBoundaries().count > 0;

const resolve = (lat, lng) => {
  const data = loadBoundaries();
  if (!data.count) return null;
  for (const f of data.features) {
    const [minX, minY, maxX, maxY] = f.bbox;
    if (lng < minX || lng > maxX || lat < minY || lat > maxY) continue;
    if (pointInRings(f.c, lng, lat)) return { state: f.s, lga: f.lga };
  }
  return null;
};

module.exports = {
  boundariesReady,
  resolve,
  normalizeKey,
  stateKeyMatches,
  lgaKeyMatches,
};
