const copy = {
  en: {
    saved_properties: 'Saved Properties',
    payment_history: 'Payment History',
    my_disputes: 'My Disputes',
    damage_reports: 'Damage Reports',
    subscription: 'Subscription',
    legal_help: 'Request Legal Help',
    support: 'Help & Support',
    saved_properties_desc: 'Check properties you saved for shortlist',
    payment_history_desc: 'Track your property detail unlock payments',
    refund_requests: 'Refund Requests',
    grace_requests: 'Grace Requests',
    available_withdraw: 'Available to Withdraw',
    rent_calculator: 'Rent Calculator',
    calculator_plan: 'Plan your rent',
    rent_calculator_title: 'Rent Calculator',
    rent_calculator_heading: 'Know your real monthly rent and your move-in total.',
    rent_calculator_intro: 'Enter a rent figure to see the monthly equivalent, full move-in cost, and how Rent Savings can help you reach it.',
    rent_details: 'Rent details',
    rent_details_subtitle: 'What the landlord is asking',
    rent_amount: 'Rent amount (NGN)',
    rent_per: 'This rent is per',
    per_year: 'Per year',
    per_month: 'Per month',
    upfront_months: 'Rent to pay upfront (months)',
    yearly_due_hint: 'Yearly quotes usually mean the full year is due at once.',
    monthly_income: 'Your monthly income (NGN) - optional',
    rent_share: 'Share of income for rent',
    rent_share_hint: 'A common guideline is around 33% of monthly income.',
    months_until_due: 'Months until rent is due - optional',
    months_until_due_hint: 'Tells you the monthly Rent Savings top-up to hit the target.',
    calculate: 'Calculate rent',
    calculating: 'Calculating...',
    enter_rent: 'Enter the rent amount to see your breakdown.',
    calculation_failed: 'Could not calculate. Try again.',
    calculator_unreachable: 'Could not reach the calculator. Try again.',
    enter_amount_prompt: 'Enter a rent amount above to see your monthly and move-in numbers.',
    monthly_equivalent_yearly: 'Monthly equivalent of a {{amount}} yearly rent', monthly_rent: 'Monthly rent', upfront_summary: '{{months}} month(s) upfront = {{amount}} of rent alone', fits_budget: 'Fits your income budget', above_budget: 'Above your income budget', money_day_one: 'Money needed on day one', usual_fees: 'Rent plus the usual Nigerian fees', agent_fee: 'Agent fee', legal_fee: 'Legal fee', caution_deposit: 'Caution deposit', agreement_fee: 'Agreement / stamp fee', service_charge: 'Service charge', move_in_total: 'Move-in total', rent_savings: 'Save toward it with Rent Savings', create_savings: 'Create a savings plan', browse_properties: 'Browse properties'
  },
  fr: {
    saved_properties: 'Biens enregistrés', payment_history: 'Historique des paiements', my_disputes: 'Mes litiges', damage_reports: 'Rapports de dommages', subscription: 'Abonnement', legal_help: 'Demander une aide juridique', support: 'Aide et assistance', refund_requests: 'Demandes de remboursement', grace_requests: 'Demandes de délai', available_withdraw: 'Disponible au retrait', rent_calculator: 'Calculateur de loyer', calculator_plan: 'Planifier votre loyer', rent_calculator_title: 'Calculateur de loyer', rent_calculator_heading: 'Connaissez votre loyer mensuel réel et votre coût d’installation.', rent_calculator_intro: 'Saisissez un loyer pour voir l’équivalent mensuel, le coût total d’installation et comment l’épargne-loyer peut vous aider.', rent_details: 'Détails du loyer', rent_details_subtitle: 'Ce que demande le propriétaire', rent_amount: 'Montant du loyer (NGN)', rent_per: 'Ce loyer est', per_year: 'Par an', per_month: 'Par mois', upfront_months: 'Loyer à payer d’avance (mois)', yearly_due_hint: 'Les loyers annuels sont généralement dus en une seule fois.', monthly_income: 'Votre revenu mensuel (NGN) - facultatif', rent_share: 'Part du revenu consacrée au loyer', rent_share_hint: 'Une recommandation courante est d’environ 33 % du revenu mensuel.', months_until_due: 'Mois avant l’échéance du loyer - facultatif', months_until_due_hint: 'Calcule le complément mensuel d’épargne-loyer nécessaire.', calculate: 'Calculer le loyer', calculating: 'Calcul en cours...', enter_rent: 'Saisissez le montant du loyer pour voir le détail.', calculation_failed: 'Calcul impossible. Réessayez.', calculator_unreachable: 'Calculateur inaccessible. Réessayez.', enter_amount_prompt: 'Saisissez un montant pour voir les chiffres mensuels et d’installation.', saved_properties_desc: 'Consultez vos biens enregistrés', payment_history_desc: 'Suivez les paiements de déblocage', monthly_equivalent_yearly: 'Équivalent mensuel d’un loyer annuel de {{amount}}', monthly_rent: 'Loyer mensuel', upfront_summary: '{{months}} mois d’avance = {{amount}} de loyer seul', fits_budget: 'Dans votre budget', above_budget: 'Au-dessus de votre budget', money_day_one: 'Montant nécessaire le premier jour', usual_fees: 'Loyer et frais habituels au Nigeria', agent_fee: 'Frais d’agence', legal_fee: 'Frais juridiques', caution_deposit: 'Dépôt de garantie', agreement_fee: 'Frais d’accord / timbre', service_charge: 'Frais de service', move_in_total: 'Total d’installation', rent_savings: 'Épargner avec Rent Savings', create_savings: 'Créer un plan d’épargne', browse_properties: 'Parcourir les biens'
  },
  ar: {
    saved_properties: 'العقارات المحفوظة', payment_history: 'سجل المدفوعات', my_disputes: 'نزاعاتي', damage_reports: 'تقارير الأضرار', subscription: 'الاشتراك', legal_help: 'طلب مساعدة قانونية', support: 'المساعدة والدعم', refund_requests: 'طلبات الاسترداد', grace_requests: 'طلبات المهلة', available_withdraw: 'المتاح للسحب', rent_calculator: 'حاسبة الإيجار', calculator_plan: 'خطط لإيجارك', rent_calculator_title: 'حاسبة الإيجار', rent_calculator_heading: 'اعرف إيجارك الشهري الحقيقي وتكلفة الانتقال.', rent_calculator_intro: 'أدخل قيمة الإيجار لمعرفة المكافئ الشهري وتكلفة الانتقال وكيف يمكن لمدخرات الإيجار مساعدتك.', rent_details: 'تفاصيل الإيجار', rent_details_subtitle: 'ما يطلبه المالك', rent_amount: 'مبلغ الإيجار (NGN)', rent_per: 'هذا الإيجار هو', per_year: 'سنويًا', per_month: 'شهريًا', upfront_months: 'الإيجار المدفوع مقدمًا (بالأشهر)', yearly_due_hint: 'عادةً يُدفع الإيجار السنوي كاملًا مرة واحدة.', monthly_income: 'دخلك الشهري (NGN) - اختياري', rent_share: 'نسبة الدخل للإيجار', rent_share_hint: 'الإرشاد الشائع يقارب 33٪ من الدخل الشهري.', months_until_due: 'الأشهر حتى استحقاق الإيجار - اختياري', months_until_due_hint: 'يحدد الإضافة الشهرية لمدخرات الإيجار للوصول إلى الهدف.', calculate: 'احسب الإيجار', calculating: 'جارٍ الحساب...', enter_rent: 'أدخل مبلغ الإيجار لرؤية التفاصيل.', calculation_failed: 'تعذر الحساب. حاول مرة أخرى.', calculator_unreachable: 'تعذر الوصول إلى الحاسبة. حاول مرة أخرى.', enter_amount_prompt: 'أدخل مبلغ الإيجار لرؤية الأرقام الشهرية وتكلفة الانتقال.'
  },
  ru: {
    saved_properties: 'Сохранённые объекты', payment_history: 'История платежей', my_disputes: 'Мои споры', damage_reports: 'Отчёты об ущербе', subscription: 'Подписка', legal_help: 'Запросить юридическую помощь', support: 'Помощь и поддержка', refund_requests: 'Запросы на возврат', grace_requests: 'Запросы отсрочки', available_withdraw: 'Доступно к выводу', rent_calculator: 'Калькулятор аренды', calculator_plan: 'Планируйте аренду', rent_calculator_title: 'Калькулятор аренды', rent_calculator_heading: 'Узнайте реальную месячную аренду и сумму въезда.', rent_calculator_intro: 'Введите сумму аренды, чтобы увидеть месячный эквивалент, полную сумму въезда и помощь Rent Savings.', rent_details: 'Детали аренды', rent_details_subtitle: 'Что запрашивает арендодатель', rent_amount: 'Сумма аренды (NGN)', rent_per: 'Период аренды', per_year: 'В год', per_month: 'В месяц', upfront_months: 'Аренда предоплатой (месяцы)', yearly_due_hint: 'Годовая аренда обычно оплачивается полностью сразу.', monthly_income: 'Ваш месячный доход (NGN) - необязательно', rent_share: 'Доля дохода на аренду', rent_share_hint: 'Ориентир обычно составляет около 33% месячного дохода.', months_until_due: 'Месяцев до оплаты аренды - необязательно', months_until_due_hint: 'Показывает ежемесячное пополнение Rent Savings для цели.', calculate: 'Рассчитать аренду', calculating: 'Расчёт...', enter_rent: 'Введите сумму аренды для расчёта.', calculation_failed: 'Не удалось рассчитать. Повторите попытку.', calculator_unreachable: 'Калькулятор недоступен. Повторите попытку.', enter_amount_prompt: 'Введите сумму аренды, чтобы увидеть месячные и въездные расходы.'
  },
  zh: {
    saved_properties: '已保存房源', payment_history: '付款记录', my_disputes: '我的纠纷', damage_reports: '损坏报告', subscription: '订阅', legal_help: '申请法律帮助', support: '帮助与支持', refund_requests: '退款请求', grace_requests: '宽限请求', available_withdraw: '可提现金额', rent_calculator: '租金计算器', calculator_plan: '规划租金', rent_calculator_title: '租金计算器', rent_calculator_heading: '了解真实月租和入住总成本。', rent_calculator_intro: '输入租金，查看月度等价金额、入住总成本以及租金储蓄如何帮助您达成目标。', rent_details: '租金详情', rent_details_subtitle: '房东要求的金额', rent_amount: '租金金额（NGN）', rent_per: '租金周期', per_year: '每年', per_month: '每月', upfront_months: '预付租金（月数）', yearly_due_hint: '年租通常需要一次性支付全年金额。', monthly_income: '您的月收入（NGN）- 可选', rent_share: '用于租金的收入比例', rent_share_hint: '常见建议约为月收入的 33%。', months_until_due: '距离租金到期（月）- 可选', months_until_due_hint: '显示达到目标所需的每月租金储蓄充值。', calculate: '计算租金', calculating: '正在计算...', enter_rent: '输入租金金额查看明细。', calculation_failed: '无法计算，请重试。', calculator_unreachable: '无法连接计算器，请重试。', enter_amount_prompt: '输入租金金额查看月度和入住数字。'
  },
  ha: {
    saved_properties: 'Gidajen da aka ajiye', payment_history: 'Tarihin biyan kuɗi', my_disputes: 'Rigimomina', damage_reports: 'Rahotannin lalacewa', subscription: 'Biyan kuɗin shiga', legal_help: 'Nemi taimakon shari’a', support: 'Taimako da tallafi', refund_requests: 'Buƙatun mayar da kuɗi', grace_requests: 'Buƙatun ƙarin lokaci', available_withdraw: 'Akwai don cirewa', rent_calculator: 'Kalkuleta na haya', calculator_plan: 'Tsara hayarka', rent_calculator_title: 'Kalkuleta na haya', rent_calculator_heading: 'San ainihin hayar wata da kuɗin shiga gida.', rent_calculator_intro: 'Shigar da haya don ganin daidai na wata, cikakken kuɗin shiga gida, da yadda ajiyar haya za ta taimaka.', rent_details: 'Bayanan haya', rent_details_subtitle: 'Abin da mai gida ke nema', rent_amount: 'Adadin haya (NGN)', rent_per: 'Wannan haya ta kasance', per_year: 'A shekara', per_month: 'A wata', upfront_months: 'Hayar da za a biya gaba (watanni)', yearly_due_hint: 'Yawanci ana biyan hayar shekara gaba ɗaya lokaci guda.', monthly_income: 'Kudin shigarka na wata (NGN) - zaɓi ne', rent_share: 'Kason kudin shiga na haya', rent_share_hint: 'Jagorar da aka saba ita ce kusan 33% na kudin shiga na wata.', months_until_due: 'Watanni kafin lokacin haya - zaɓi ne', months_until_due_hint: 'Yana nuna ƙarin ajiyar haya na wata don cimma manufa.', calculate: 'Lissafa haya', calculating: 'Ana lissafawa...', enter_rent: 'Shigar da adadin haya don ganin bayanin.', calculation_failed: 'An kasa lissafawa. Sake gwadawa.', calculator_unreachable: 'Ba a iya samun kalkuleta ba. Sake gwadawa.', enter_amount_prompt: 'Shigar da adadin haya don ganin kuɗin wata da shiga gida.'
  },
  yo: {
    saved_properties: 'Àwọn ilé tí a fipamọ́', payment_history: 'Ìtàn ìsanwó', my_disputes: 'Àwọn àríyànjiyàn mi', damage_reports: 'Àwọn ìròyìn ìbàjẹ́', subscription: 'Ìforúkọsílẹ̀', legal_help: 'Béèrè ìrànwọ́ òfin', support: 'Ìrànwọ́ àti àtìlẹ́yìn', refund_requests: 'Àwọn ìbéèrè ìdápadà owó', grace_requests: 'Àwọn ìbéèrè àfikún àkókò', available_withdraw: 'Owó tó wà fún yíyọ̀', rent_calculator: 'Ẹrọ ìṣirò yàrá', calculator_plan: 'Gbé ètò yàrá rẹ kalẹ̀', rent_calculator_title: 'Ẹrọ ìṣirò yàrá', rent_calculator_heading: 'Mọ owó yàrá oṣù rẹ àti iye owó ìgbé wọlé.', rent_calculator_intro: 'Tẹ iye yàrá sílẹ̀ láti rí ìdọ́gba oṣù, iye ìgbé wọlé, àti bí Rent Savings ṣe lè ràn ọ́ lọ́wọ́.', rent_details: 'Àlàyé yàrá', rent_details_subtitle: 'Ohun tí onílé ń béèrè', rent_amount: 'Iye yàrá (NGN)', rent_per: 'Yàrá yìí jẹ́', per_year: 'Ní ọdún', per_month: 'Ní oṣù', upfront_months: 'Yàrá tí a máa san ṣáájú (oṣù)', yearly_due_hint: 'A máa ń san yàrá ọdún ní ẹẹkan.', monthly_income: 'Owó tí o ń wọlé lóṣù (NGN) - àṣàyàn', rent_share: 'Ìpín owó wọlé fún yàrá', rent_share_hint: 'Ìtọ́sọ́nà tí a mọ̀ ni nǹkan bí 33% owó wọlé oṣù.', months_until_due: 'Oṣù mélòó ni ó kù sí ìsanwó - àṣàyàn', months_until_due_hint: 'Ó fi àfikún Rent Savings oṣù hàn láti dé ibi-afẹ́.', calculate: 'Ṣírò yàrá', calculating: 'Ó ń ṣírò...', enter_rent: 'Tẹ iye yàrá láti rí àlàyé.', calculation_failed: 'A kò lè ṣírò. Gbìyànjú lẹ́ẹ̀kan síi.', calculator_unreachable: 'A kò lè dé ẹrọ ìṣirò. Gbìyànjú lẹ́ẹ̀kan síi.', enter_amount_prompt: 'Tẹ iye yàrá láti rí iye oṣù àti owó ìgbé wọlé.'
  },
  ig: {
    saved_properties: 'Ụlọ echekwara', payment_history: 'Akụkọ ịkwụ ụgwọ', my_disputes: 'Esemokwu m', damage_reports: 'Akụkọ mmebi', subscription: 'Ndebanye aha', legal_help: 'Rịọ enyemaka iwu', support: 'Enyemaka na nkwado', refund_requests: 'Arịrịọ nkwụghachi', grace_requests: 'Arịrịọ oge ọzọ', available_withdraw: 'Ego dị maka iwepụ', rent_calculator: 'Ngwa ịgbakọ ụgwọ ụlọ', calculator_plan: 'Hazie ụgwọ ụlọ gị', rent_calculator_title: 'Ngwa ịgbakọ ụgwọ ụlọ', rent_calculator_heading: 'Mara ụgwọ ụlọ kwa ọnwa na ego ị ga-eji banye.', rent_calculator_intro: 'Tinye ego ụlọ ka ị hụ nke kwa ọnwa, ụgwọ ịbanye, na otu Rent Savings ga-esi nyere gị aka.', rent_details: 'Nkọwa ụgwọ ụlọ', rent_details_subtitle: 'Ihe onye nwe ụlọ chọrọ', rent_amount: 'Ego ụlọ (NGN)', rent_per: 'Ụgwọ a bụ', per_year: 'Kwa afọ', per_month: 'Kwa ọnwa', upfront_months: 'Ụgwọ ụlọ a ga-akwụ tupu oge (ọnwa)', yearly_due_hint: 'A na-akwụkarị ụgwọ ụlọ kwa afọ niile n’otu oge.', monthly_income: 'Ego ị na-enweta kwa ọnwa (NGN) - nhọrọ', rent_share: 'Akụkụ ego maka ụlọ', rent_share_hint: 'Ndụmọdụ a na-ahụkarị bụ ihe dịka 33% nke ego kwa ọnwa.', months_until_due: 'Ọnwa ruo mgbe ụgwọ ruru - nhọrọ', months_until_due_hint: 'Ọ na-egosi ego Rent Savings kwa ọnwa iji ruo ebumnuche.', calculate: 'Gbakọọ ụgwọ ụlọ', calculating: 'Na-agbakọ...', enter_rent: 'Tinye ego ụlọ ka ị hụ nkọwa.', calculation_failed: 'Enweghị ike ịgbakọ. Gbalịa ọzọ.', calculator_unreachable: 'Enweghị ike iru ngwa ịgbakọ. Gbalịa ọzọ.', enter_amount_prompt: 'Tinye ego ụlọ ka ị hụ ọnụ ahịa kwa ọnwa na ịbanye.'
  },
};

const resultCopy = {
  en: { saved_properties_desc: 'Check properties you saved for shortlist', payment_history_desc: 'Track your property detail unlock payments', monthly_equivalent_yearly: 'Monthly equivalent of a {{amount}} yearly rent', monthly_rent: 'Monthly rent', upfront_summary: '{{months}} month(s) upfront = {{amount}} of rent alone', fits_budget: 'Fits your income budget', above_budget: 'Above your income budget', money_day_one: 'Money needed on day one', usual_fees: 'Rent plus the usual Nigerian fees', agent_fee: 'Agent fee', legal_fee: 'Legal fee', caution_deposit: 'Caution deposit', agreement_fee: 'Agreement / stamp fee', service_charge: 'Service charge', move_in_total: 'Move-in total', rent_savings: 'Save toward it with Rent Savings', create_savings: 'Create a savings plan', browse_properties: 'Browse properties', negotiation: 'Negotiation', loading_details: 'Loading application details...', property: 'Property', listed_rent: 'Listed rent', current_rent: 'Current working rent', application_status: 'Application status', negotiation_history: 'Negotiation history', no_events: 'No negotiation events yet.', tenant_actions: 'Tenant actions', landlord_actions: 'Landlord actions', offer_control: 'Offer control', open_negotiation: 'Open negotiation', send_offer: 'Send offer', sending: 'Sending...', saving: 'Saving...', accept_counter: 'Accept counter', reject_counter: 'Reject counter', approve_application: 'Approve application', approving: 'Approving...', reject_application: 'Reject application', rejecting: 'Rejecting...', accept_tenant_offer: 'Accept tenant offer', send_counter: 'Send counter-offer', current_counter: 'Current counter-offer', no_counter: 'No landlord counter-offer is waiting for your response.', tenant_proposed: 'Tenant proposed', no_offer: 'The tenant has not submitted a rent offer yet.', optional_note: 'Optional note', counter_rent: 'Enter counter-offer rent', action_success: 'Action completed', action_failed: 'Action failed', offer_sent: 'Offer sent to landlord', counter_accepted: 'Counter-offer accepted', counter_rejected: 'Counter-offer rejected', application_approved: 'Application approved', application_rejected: 'Application rejected', tenant_offer_accepted: 'Tenant offer accepted', counter_sent: 'Counter-offer sent', accept: 'Accept', reject: 'Reject', status_none: 'No offer', status_tenant_offered: 'Tenant offer', status_landlord_countered: 'Landlord counter-offer', status_agreed: 'Agreed', status_declined: 'Declined', action_tenant_offer: 'Tenant offer', action_landlord_counter: 'Landlord counter-offer', action_landlord_accept: 'Landlord accepted offer', action_tenant_accept: 'Tenant accepted counter-offer', action_tenant_reject: 'Tenant rejected counter-offer' },
  fr: { saved_properties_desc: 'Consultez vos biens enregistrés', payment_history_desc: 'Suivez les paiements de déblocage', monthly_equivalent_yearly: 'Équivalent mensuel d’un loyer annuel de {{amount}}', monthly_rent: 'Loyer mensuel', upfront_summary: '{{months}} mois d’avance = {{amount}} de loyer seul', fits_budget: 'Dans votre budget', above_budget: 'Au-dessus de votre budget', money_day_one: 'Montant nécessaire le premier jour', usual_fees: 'Loyer et frais habituels au Nigeria', agent_fee: 'Frais d’agence', legal_fee: 'Frais juridiques', caution_deposit: 'Dépôt de garantie', agreement_fee: 'Frais d’accord / timbre', service_charge: 'Frais de service', move_in_total: 'Total d’installation', rent_savings: 'Épargner avec Rent Savings', create_savings: 'Créer un plan d’épargne', browse_properties: 'Parcourir les biens', negotiation: 'Négociation', loading_details: 'Chargement des détails...', property: 'Bien', listed_rent: 'Loyer indiqué', current_rent: 'Loyer actuel', application_status: 'Statut de candidature', negotiation_history: 'Historique de négociation', no_events: 'Aucun événement de négociation.', tenant_actions: 'Actions du locataire', landlord_actions: 'Actions du propriétaire', offer_control: 'Gestion des offres', open_negotiation: 'Ouvrir la négociation', send_offer: 'Envoyer l’offre', sending: 'Envoi...', saving: 'Enregistrement...', accept_counter: 'Accepter la contre-offre', reject_counter: 'Refuser la contre-offre', approve_application: 'Approuver la candidature', approving: 'Approbation...', reject_application: 'Refuser la candidature', rejecting: 'Refus...', accept_tenant_offer: 'Accepter l’offre du locataire', send_counter: 'Envoyer une contre-offre', current_counter: 'Contre-offre actuelle', no_counter: 'Aucune contre-offre du propriétaire n’attend votre réponse.', tenant_proposed: 'Proposition du locataire', no_offer: 'Le locataire n’a pas encore envoyé d’offre.', optional_note: 'Note facultative', counter_rent: 'Saisissez la contre-offre', action_success: 'Action terminée', action_failed: 'Échec de l’action', offer_sent: 'Offre envoyée au propriétaire', counter_accepted: 'Contre-offre acceptée', counter_rejected: 'Contre-offre refusée', application_approved: 'Candidature approuvée', application_rejected: 'Candidature refusée', tenant_offer_accepted: 'Offre du locataire acceptée', counter_sent: 'Contre-offre envoyée', accept: 'Accepter', reject: 'Refuser', status_none: 'Aucune offre', status_tenant_offered: 'Offre du locataire', status_landlord_countered: 'Contre-offre du propriétaire', status_agreed: 'Accordé', status_declined: 'Refusé', action_tenant_offer: 'Offre du locataire', action_landlord_counter: 'Contre-offre du propriétaire', action_landlord_accept: 'Offre acceptée par le propriétaire', action_tenant_accept: 'Contre-offre acceptée par le locataire', action_tenant_reject: 'Contre-offre refusée par le locataire' },
  ar: { saved_properties_desc: 'تحقق من العقارات التي حفظتها', payment_history_desc: 'تابع مدفوعات فتح تفاصيل العقار', monthly_equivalent_yearly: 'المكافئ الشهري لإيجار سنوي قدره {{amount}}', monthly_rent: 'الإيجار الشهري', upfront_summary: '{{months}} أشهر مقدمًا = {{amount}} للإيجار فقط', fits_budget: 'يناسب ميزانيتك', above_budget: 'أعلى من ميزانيتك', money_day_one: 'المبلغ المطلوب في اليوم الأول', usual_fees: 'الإيجار والرسوم المعتادة في نيجيريا', agent_fee: 'رسوم الوكيل', legal_fee: 'الرسوم القانونية', caution_deposit: 'تأمين الضمان', agreement_fee: 'رسوم الاتفاق / الطابع', service_charge: 'رسوم الخدمة', move_in_total: 'إجمالي الانتقال', rent_savings: 'ادخر عبر Rent Savings', create_savings: 'إنشاء خطة ادخار', browse_properties: 'تصفح العقارات', negotiation: 'التفاوض', loading_details: 'جارٍ تحميل التفاصيل...', property: 'العقار', listed_rent: 'الإيجار المدرج', current_rent: 'الإيجار الحالي', application_status: 'حالة الطلب', negotiation_history: 'سجل التفاوض', no_events: 'لا توجد أحداث تفاوض بعد.', tenant_actions: 'إجراءات المستأجر', landlord_actions: 'إجراءات المالك', offer_control: 'إدارة العروض', open_negotiation: 'فتح التفاوض', send_offer: 'إرسال العرض', sending: 'جارٍ الإرسال...', saving: 'جارٍ الحفظ...', accept_counter: 'قبول العرض المضاد', reject_counter: 'رفض العرض المضاد', approve_application: 'قبول الطلب', approving: 'جارٍ القبول...', reject_application: 'رفض الطلب', rejecting: 'جارٍ الرفض...', accept_tenant_offer: 'قبول عرض المستأجر', send_counter: 'إرسال عرض مضاد', current_counter: 'العرض المضاد الحالي', no_counter: 'لا يوجد عرض مضاد من المالك بانتظار ردك.', tenant_proposed: 'عرض المستأجر', no_offer: 'لم يرسل المستأجر عرضًا بعد.', optional_note: 'ملاحظة اختيارية', counter_rent: 'أدخل الإيجار المقترح المضاد', action_success: 'اكتمل الإجراء', action_failed: 'فشل الإجراء', offer_sent: 'تم إرسال العرض إلى المالك', counter_accepted: 'تم قبول العرض المضاد', counter_rejected: 'تم رفض العرض المضاد', application_approved: 'تم قبول الطلب', application_rejected: 'تم رفض الطلب', tenant_offer_accepted: 'تم قبول عرض المستأجر', counter_sent: 'تم إرسال العرض المضاد', accept: 'قبول', reject: 'رفض', status_none: 'لا يوجد عرض', status_tenant_offered: 'عرض المستأجر', status_landlord_countered: 'عرض المالك المضاد', status_agreed: 'متفق عليه', status_declined: 'مرفوض', action_tenant_offer: 'عرض المستأجر', action_landlord_counter: 'عرض المالك المضاد', action_landlord_accept: 'قبل المالك العرض', action_tenant_accept: 'قبل المستأجر العرض المضاد', action_tenant_reject: 'رفض المستأجر العرض المضاد' },
  ru: { saved_properties_desc: 'Откройте сохранённые объекты', payment_history_desc: 'Отслеживайте платежи за открытие деталей', monthly_equivalent_yearly: 'Месячный эквивалент годовой аренды {{amount}}', monthly_rent: 'Месячная аренда', upfront_summary: '{{months}} месяцев вперёд = {{amount}} только аренды', fits_budget: 'Вписывается в ваш бюджет', above_budget: 'Выше вашего бюджета', money_day_one: 'Сумма на первый день', usual_fees: 'Аренда и обычные сборы в Нигерии', agent_fee: 'Комиссия агента', legal_fee: 'Юридический сбор', caution_deposit: 'Залог', agreement_fee: 'Сбор за соглашение / гербовый сбор', service_charge: 'Сервисный сбор', move_in_total: 'Общая сумма въезда', rent_savings: 'Копите с Rent Savings', create_savings: 'Создать план накоплений', browse_properties: 'Просмотреть объекты', negotiation: 'Переговоры', loading_details: 'Загрузка деталей...', property: 'Объект', listed_rent: 'Указанная аренда', current_rent: 'Текущая аренда', application_status: 'Статус заявки', negotiation_history: 'История переговоров', no_events: 'Событий переговоров пока нет.', tenant_actions: 'Действия арендатора', landlord_actions: 'Действия арендодателя', offer_control: 'Управление предложениями', open_negotiation: 'Открыть переговоры', send_offer: 'Отправить предложение', sending: 'Отправка...', saving: 'Сохранение...', accept_counter: 'Принять встречное предложение', reject_counter: 'Отклонить встречное предложение', approve_application: 'Одобрить заявку', approving: 'Одобрение...', reject_application: 'Отклонить заявку', rejecting: 'Отклонение...', accept_tenant_offer: 'Принять предложение арендатора', send_counter: 'Отправить встречное предложение', current_counter: 'Текущее встречное предложение', no_counter: 'Встречного предложения арендодателя для ответа нет.', tenant_proposed: 'Предложение арендатора', no_offer: 'Арендатор ещё не отправил предложение.', optional_note: 'Необязательная заметка', counter_rent: 'Введите встречную аренду', action_success: 'Действие выполнено', action_failed: 'Действие не выполнено', offer_sent: 'Предложение отправлено арендодателю', counter_accepted: 'Встречное предложение принято', counter_rejected: 'Встречное предложение отклонено', application_approved: 'Заявка одобрена', application_rejected: 'Заявка отклонена', tenant_offer_accepted: 'Предложение арендатора принято', counter_sent: 'Встречное предложение отправлено', accept: 'Принять', reject: 'Отклонить', status_none: 'Нет предложения', status_tenant_offered: 'Предложение арендатора', status_landlord_countered: 'Встречное предложение арендодателя', status_agreed: 'Согласовано', status_declined: 'Отклонено', action_tenant_offer: 'Предложение арендатора', action_landlord_counter: 'Встречное предложение арендодателя', action_landlord_accept: 'Арендодатель принял предложение', action_tenant_accept: 'Арендатор принял встречное предложение', action_tenant_reject: 'Арендатор отклонил встречное предложение' },
  zh: { saved_properties_desc: '查看您保存的房源', payment_history_desc: '跟踪房源详情解锁付款', monthly_equivalent_yearly: '年租 {{amount}} 的月度等价金额', monthly_rent: '月租', upfront_summary: '预付 {{months}} 个月 = 仅租金 {{amount}}', fits_budget: '符合您的收入预算', above_budget: '超过您的收入预算', money_day_one: '第一天所需金额', usual_fees: '租金及尼日利亚常见费用', agent_fee: '代理费', legal_fee: '法律费用', caution_deposit: '押金', agreement_fee: '协议 / 印花费', service_charge: '服务费', move_in_total: '入住总额', rent_savings: '使用 Rent Savings 储蓄', create_savings: '创建储蓄计划', browse_properties: '浏览房源' },
  ha: { saved_properties_desc: 'Duba gidajen da ka ajiye', payment_history_desc: 'Bibiyi biyan kuɗin buɗe bayanan gida', monthly_equivalent_yearly: 'Daidaiton wata na hayar shekara {{amount}}', monthly_rent: 'Hayar wata', upfront_summary: 'Watanni {{months}} gaba = {{amount}} na haya kaɗai', fits_budget: 'Ya dace da kasafin kudin shiga', above_budget: 'Ya wuce kasafin kudin shiga', money_day_one: 'Kuɗin da ake buƙata ranar farko', usual_fees: 'Haya da kuɗaɗen da aka saba a Najeriya', agent_fee: 'Kuɗin wakili', legal_fee: 'Kuɗin shari’a', caution_deposit: 'Ajiyar garanti', agreement_fee: 'Kuɗin yarjejeniya / hatimi', service_charge: 'Kuɗin sabis', move_in_total: 'Jimillar shiga gida', rent_savings: 'Ajiye ta Rent Savings', create_savings: 'Ƙirƙiri tsarin ajiya', browse_properties: 'Duba gidaje' },
  yo: { saved_properties_desc: 'Ṣàyẹ̀wò àwọn ilé tí o fipamọ́', payment_history_desc: 'Tọpinpin ìsanwó ṣíṣí àlàyé ilé', monthly_equivalent_yearly: 'Ìdọ́gba oṣù ti yàrá ọdún {{amount}}', monthly_rent: 'Yàrá oṣù', upfront_summary: 'Oṣù {{months}} ṣáájú = {{amount}} ti yàrá nìkan', fits_budget: 'Ó bá ètò owó wọlé rẹ mu', above_budget: 'Ó ju ètò owó wọlé rẹ lọ', money_day_one: 'Owó tí a nílò ní ọjọ́ àkọ́kọ́', usual_fees: 'Yàrá àti owó tí a máa ń san ní Nàìjíríà', agent_fee: 'Owó aṣojú', legal_fee: 'Owó òfin', caution_deposit: 'Owó ìdánilójú', agreement_fee: 'Owó ìfohùnṣọ̀kan / stamp', service_charge: 'Owó iṣẹ́', move_in_total: 'Àpapọ̀ owó ìgbé wọlé', rent_savings: 'Fi Rent Savings pamọ́ sí i', create_savings: 'Ṣẹ̀dá ètò ìfipamọ́', browse_properties: 'Ṣàyẹ̀wò àwọn ilé' },
  ig: { saved_properties_desc: 'Lelee ụlọ ndị ị chekwara', payment_history_desc: 'Soro ịkwụ ụgwọ imeghe nkọwa ụlọ', monthly_equivalent_yearly: 'Ọnụ kwa ọnwa nke ụlọ kwa afọ {{amount}}', monthly_rent: 'Ụgwọ ụlọ kwa ọnwa', upfront_summary: 'Ọnwa {{months}} tupu oge = {{amount}} naanị ụgwọ ụlọ', fits_budget: 'Ọ dabara na mmefu ego gị', above_budget: 'Ọ karịrị mmefu ego gị', money_day_one: 'Ego achọrọ n’ụbọchị mbụ', usual_fees: 'Ụgwọ ụlọ na ụgwọ a na-ahụkarị na Naịjirịa', agent_fee: 'Ụgwọ onye nnọchi anya', legal_fee: 'Ụgwọ iwu', caution_deposit: 'Ego nkwụnye nchebe', agreement_fee: 'Ụgwọ nkwekọrịta / stampụ', service_charge: 'Ụgwọ ọrụ', move_in_total: 'Ngụkọta ego ịbanye', rent_savings: 'Chekwaa site na Rent Savings', create_savings: 'Mepụta atụmatụ nchekwa', browse_properties: 'Chọgharịa ụlọ' },
};

const negotiationCopy = {
  zh: { negotiation: '协商', loading_details: '正在加载申请详情...', property: '房源', listed_rent: '标示租金', current_rent: '当前租金', application_status: '申请状态', negotiation_history: '协商记录', no_events: '暂无协商记录。', offer_control: '报价管理', open_negotiation: '打开协商', send_offer: '发送报价', sending: '发送中...', saving: '保存中...', accept_counter: '接受还价', reject_counter: '拒绝还价', approve_application: '批准申请', approving: '批准中...', reject_application: '拒绝申请', rejecting: '拒绝中...', accept_tenant_offer: '接受租客报价', send_counter: '发送还价', current_counter: '当前还价', no_counter: '暂无等待您回复的房东还价。', tenant_proposed: '租客报价', no_offer: '租客尚未提交报价。', optional_note: '可选备注', counter_rent: '输入还价租金', action_failed: '操作失败', offer_sent: '报价已发送给房东', counter_accepted: '还价已接受', counter_rejected: '还价已拒绝', application_approved: '申请已批准', application_rejected: '申请已拒绝', tenant_offer_accepted: '租客报价已接受', counter_sent: '还价已发送', status_none: '无报价', status_tenant_offered: '租客报价', status_landlord_countered: '房东还价', status_agreed: '已同意', status_declined: '已拒绝', action_tenant_offer: '租客报价', action_landlord_counter: '房东还价', action_landlord_accept: '房东接受报价', action_tenant_accept: '租客接受还价', action_tenant_reject: '租客拒绝还价' },
  ha: { negotiation: 'Tattaunawa', loading_details: 'Ana loda bayanan aikace-aikace...', property: 'Gida', listed_rent: 'Hayar da aka nuna', current_rent: 'Hayar yanzu', application_status: 'Matsayin aikace-aikace', negotiation_history: 'Tarihin tattaunawa', no_events: 'Babu abubuwan tattaunawa tukuna.', offer_control: 'Sarrafa tayin', open_negotiation: 'Buɗe tattaunawa', send_offer: 'Aika tayi', sending: 'Ana aikawa...', saving: 'Ana ajiyewa...', accept_counter: 'Karɓi tayin amsa', reject_counter: 'Ƙi tayin amsa', approve_application: 'Amince da aikace-aikace', approving: 'Ana amincewa...', reject_application: 'Ƙi aikace-aikace', rejecting: 'Ana ƙi...', accept_tenant_offer: 'Karɓi tayin mai haya', send_counter: 'Aika tayin amsa', current_counter: 'Tayin amsa na yanzu', no_counter: 'Babu tayin amsa daga mai gida da ke jiran amsarka.', tenant_proposed: 'Tayin mai haya', no_offer: 'Mai haya bai aika tayi ba tukuna.', optional_note: 'Bayanin zaɓi', counter_rent: 'Shigar da hayar tayin amsa', action_failed: 'Aiki ya gaza', offer_sent: 'An aika tayi ga mai gida', counter_accepted: 'An karɓi tayin amsa', counter_rejected: 'An ƙi tayin amsa', application_approved: 'An amince da aikace-aikace', application_rejected: 'An ƙi aikace-aikace', tenant_offer_accepted: 'An karɓi tayin mai haya', counter_sent: 'An aika tayin amsa', status_none: 'Babu tayi', status_tenant_offered: 'Tayin mai haya', status_landlord_countered: 'Tayin amsa na mai gida', status_agreed: 'An yarda', status_declined: 'An ƙi', action_tenant_offer: 'Tayin mai haya', action_landlord_counter: 'Tayin amsa na mai gida', action_landlord_accept: 'Mai gida ya karɓi tayi', action_tenant_accept: 'Mai haya ya karɓi tayin amsa', action_tenant_reject: 'Mai haya ya ƙi tayin amsa' },
  yo: { negotiation: 'Ìjíròrò', loading_details: 'Ó ń kó àlàyé ìbéèrè...', property: 'Ilé', listed_rent: 'Yàrá tí a kọ sílẹ̀', current_rent: 'Yàrá tó wà báyìí', application_status: 'Ipò ìbéèrè', negotiation_history: 'Ìtàn ìjíròrò', no_events: 'Kò sí ìṣẹ̀lẹ̀ ìjíròrò síbẹ̀.', offer_control: 'Ìṣàkóso àbá', open_negotiation: 'Ṣí ìjíròrò', send_offer: 'Rán àbá', sending: 'Ó ń ránṣẹ́...', saving: 'Ó ń fipamọ́...', accept_counter: 'Gba àbá ìdáhùn', reject_counter: 'Kọ àbá ìdáhùn', approve_application: 'Fọwọ́sí ìbéèrè', approving: 'Ó ń fọwọ́sí...', reject_application: 'Kọ ìbéèrè', rejecting: 'Ó ń kọ...', accept_tenant_offer: 'Gba àbá ayálégbé', send_counter: 'Rán àbá ìdáhùn', current_counter: 'Àbá ìdáhùn tó wà', no_counter: 'Kò sí àbá ìdáhùn onílé tó ń dúró de ìdáhùn rẹ.', tenant_proposed: 'Àbá ayálégbé', no_offer: 'Ayálégbé kò tíì rán àbá.', optional_note: 'Àkọsílẹ̀ àṣàyàn', counter_rent: 'Tẹ yàrá àbá ìdáhùn', action_failed: 'Ìṣe kùnà', offer_sent: 'A ti rán àbá sí onílé', counter_accepted: 'A gba àbá ìdáhùn', counter_rejected: 'A kọ àbá ìdáhùn', application_approved: 'A fọwọ́sí ìbéèrè', application_rejected: 'A kọ ìbéèrè', tenant_offer_accepted: 'A gba àbá ayálégbé', counter_sent: 'A ti rán àbá ìdáhùn', status_none: 'Kò sí àbá', status_tenant_offered: 'Àbá ayálégbé', status_landlord_countered: 'Àbá ìdáhùn onílé', status_agreed: 'A ti fohùnṣọ̀kan', status_declined: 'A kọ́', action_tenant_offer: 'Àbá ayálégbé', action_landlord_counter: 'Àbá ìdáhùn onílé', action_landlord_accept: 'Onílé gba àbá', action_tenant_accept: 'Ayálégbé gba àbá ìdáhùn', action_tenant_reject: 'Ayálégbé kọ àbá ìdáhùn' },
  ig: { negotiation: 'Mkparịta ụka', loading_details: 'Na-ebudata nkọwa ngwa...', property: 'Ụlọ', listed_rent: 'Ụgwọ ụlọ edere', current_rent: 'Ụgwọ ụlọ ugbu a', application_status: 'Ọnọdụ ngwa', negotiation_history: 'Akụkọ mkparịta ụka', no_events: 'Enweghị ihe mkparịta ụka ugbu a.', offer_control: 'Njikwa onyinye', open_negotiation: 'Mepee mkparịta ụka', send_offer: 'Zipu onyinye', sending: 'Na-eziga...', saving: 'Na-echekwa...', accept_counter: 'Nabata nzaghachi', reject_counter: 'Jụ nzaghachi', approve_application: 'Kwado ngwa', approving: 'Na-akwado...', reject_application: 'Jụ ngwa', rejecting: 'Na-ajụ...', accept_tenant_offer: 'Nabata onyinye onye bi n’ụlọ', send_counter: 'Zipu nzaghachi', current_counter: 'Nzaghachi ugbu a', no_counter: 'Enweghị nzaghachi onye nwe ụlọ na-eche azịza gị.', tenant_proposed: 'Onyinye onye bi n’ụlọ', no_offer: 'Onye bi n’ụlọ ezibeghị onyinye.', optional_note: 'Ihe edere nhọrọ', counter_rent: 'Tinye ụgwọ nzaghachi', action_failed: 'Omume dara', offer_sent: 'E zigara onye nwe ụlọ onyinye', counter_accepted: 'Anabatara nzaghachi', counter_rejected: 'Ajụrụ nzaghachi', application_approved: 'A kwadoro ngwa', application_rejected: 'Ajụrụ ngwa', tenant_offer_accepted: 'Anabatara onyinye onye bi n’ụlọ', counter_sent: 'E zigara nzaghachi', status_none: 'Enweghị onyinye', status_tenant_offered: 'Onyinye onye bi n’ụlọ', status_landlord_countered: 'Nzaghachi onye nwe ụlọ', status_agreed: 'Kwenyere', status_declined: 'Ajụrụ', action_tenant_offer: 'Onyinye onye bi n’ụlọ', action_landlord_counter: 'Nzaghachi onye nwe ụlọ', action_landlord_accept: 'Onye nwe ụlọ nabatara onyinye', action_tenant_accept: 'Onye bi n’ụlọ nabatara nzaghachi', action_tenant_reject: 'Onye bi n’ụlọ jụrụ nzaghachi' },
};

const destinationStatusCopy = {
  en: { in_label: 'in', priority_low: 'Low', priority_normal: 'Normal', priority_high: 'High', priority_urgent: 'Urgent', damage_draft: 'Draft', damage_published: 'Published', transport_pending: 'Pending', transport_confirmed: 'Confirmed', transport_completed: 'Completed', transport_cancelled: 'Cancelled', property_location: 'Property location', verification_submitted: 'Verification Submitted', view_verification: 'View Verification Status', verification_rejected: 'Verification Rejected', pay_property_details: 'Pay Per Property Details', browse_properties: 'Browse Properties', withdrawal_notice: 'Rent Payment Withdrawals', registration_prefill: 'Your registration location is prefilled below so tenant discovery and landlord posting stay aligned. You can still change it for this property.', assigned_landlord_notice: 'You are adding this property on behalf of your assigned landlord.' },
  fr: { in_label: 'dans', priority_low: 'Faible', priority_normal: 'Normal', priority_high: 'Élevé', priority_urgent: 'Urgent', damage_draft: 'Brouillon', damage_published: 'Publié', transport_pending: 'En attente', transport_confirmed: 'Confirmé', transport_completed: 'Terminé', transport_cancelled: 'Annulé', property_location: 'Emplacement du bien', verification_submitted: 'Vérification envoyée', view_verification: 'Voir le statut de vérification', verification_rejected: 'Vérification refusée', pay_property_details: 'Payer pour les détails du bien', browse_properties: 'Parcourir les biens', withdrawal_notice: 'Retraits des paiements de loyer', registration_prefill: 'Votre emplacement d’inscription est prérempli afin d’aligner la recherche des locataires et les annonces. Vous pouvez encore le modifier.', assigned_landlord_notice: 'Vous ajoutez ce bien pour le compte de votre propriétaire assigné.' },
  ar: { in_label: 'في', priority_low: 'منخفض', priority_normal: 'عادي', priority_high: 'مرتفع', priority_urgent: 'عاجل', damage_draft: 'مسودة', damage_published: 'منشور', transport_pending: 'قيد الانتظار', transport_confirmed: 'مؤكد', transport_completed: 'مكتمل', transport_cancelled: 'ملغى', property_location: 'موقع العقار', verification_submitted: 'تم إرسال التحقق', view_verification: 'عرض حالة التحقق', verification_rejected: 'تم رفض التحقق', pay_property_details: 'ادفع لعرض تفاصيل العقار', browse_properties: 'تصفح العقارات', withdrawal_notice: 'سحوبات مدفوعات الإيجار', registration_prefill: 'تم ملء موقع تسجيلك مسبقًا لمواءمة اكتشاف المستأجرين ونشر المالك. يمكنك تغييره لهذا العقار.', assigned_landlord_notice: 'أنت تضيف هذا العقار نيابةً عن المالك المعيّن.' },
  ru: { in_label: 'в', priority_low: 'Низкий', priority_normal: 'Обычный', priority_high: 'Высокий', priority_urgent: 'Срочный', damage_draft: 'Черновик', damage_published: 'Опубликовано', transport_pending: 'Ожидание', transport_confirmed: 'Подтверждено', transport_completed: 'Завершено', transport_cancelled: 'Отменено', property_location: 'Расположение объекта', verification_submitted: 'Проверка отправлена', view_verification: 'Статус проверки', verification_rejected: 'Проверка отклонена', pay_property_details: 'Оплатить детали объекта', browse_properties: 'Просмотреть объекты', withdrawal_notice: 'Вывод арендных платежей', registration_prefill: 'Место регистрации заполнено заранее, чтобы согласовать поиск арендаторов и публикацию. Его можно изменить.', assigned_landlord_notice: 'Вы добавляете объект от имени назначенного арендодателя.' },
  zh: { in_label: '位于', priority_low: '低', priority_normal: '普通', priority_high: '高', priority_urgent: '紧急', damage_draft: '草稿', damage_published: '已发布', transport_pending: '待处理', transport_confirmed: '已确认', transport_completed: '已完成', transport_cancelled: '已取消', property_location: '房源位置', verification_submitted: '验证已提交', view_verification: '查看验证状态', verification_rejected: '验证被拒绝', pay_property_details: '付费查看房源详情', browse_properties: '浏览房源', withdrawal_notice: '租金付款提现', registration_prefill: '您的注册位置已预填，以保持租客发现和房东发布一致。您仍可为此房源修改。', assigned_landlord_notice: '您正在代表分配的房东添加此房源。' },
  ha: { in_label: 'a cikin', priority_low: 'Ƙasa', priority_normal: 'Na al’ada', priority_high: 'Mai girma', priority_urgent: 'Gaggawa', damage_draft: 'Daftari', damage_published: 'An buga', transport_pending: 'Ana jira', transport_confirmed: 'An tabbatar', transport_completed: 'An kammala', transport_cancelled: 'An soke', property_location: 'Wurin gida', verification_submitted: 'An aika tabbatarwa', view_verification: 'Duba matsayin tabbatarwa', verification_rejected: 'An ƙi tabbatarwa', pay_property_details: 'Biya don bayanan gida', browse_properties: 'Duba gidaje', withdrawal_notice: 'Cire kuɗin biyan haya', registration_prefill: 'An cika wurin rajistarka domin daidaita binciken masu haya da tallan masu gida. Za ka iya canza shi.', assigned_landlord_notice: 'Kana ƙara wannan gida a madadin mai gidanka da aka sanya.' },
  yo: { in_label: 'nínú', priority_low: 'Kéré', priority_normal: 'Déédé', priority_high: 'Gíga', priority_urgent: 'Pàtàkì', damage_draft: 'Àkọ́kọ́rọ́', damage_published: 'A tẹ̀jáde', transport_pending: 'Ń dúró', transport_confirmed: 'A fìdí rẹ̀ múlẹ̀', transport_completed: 'A parí', transport_cancelled: 'A fagilé', property_location: 'Ibi ilé', verification_submitted: 'A ti fi ìmúdájú ránṣẹ́', view_verification: 'Wo ipò ìmúdájú', verification_rejected: 'A kọ ìmúdájú', pay_property_details: 'Sanwó fún àlàyé ilé', browse_properties: 'Ṣàyẹ̀wò àwọn ilé', withdrawal_notice: 'Yíyọ̀ọ́ owó ìsanwó yíyà', registration_prefill: 'A ti kún ibi ìforúkọsílẹ̀ rẹ̀ láti mú ìwádìí ayálégbé àti ìpolówó onílé bá ara wọn mu. O lè yí i padà.', assigned_landlord_notice: 'O ń fi ilé yìí kún fún onílé tí a yàn fún ọ.' },
  ig: { in_label: 'na', priority_low: 'Obere', priority_normal: 'Nkịtị', priority_high: 'Elu', priority_urgent: 'Ngwa ngwa', damage_draft: 'Ihe edere', damage_published: 'E bipụtara', transport_pending: 'Na-eche', transport_confirmed: 'Ekwenyere', transport_completed: 'Emechara', transport_cancelled: 'Kagbuo', property_location: 'Ebe ụlọ', verification_submitted: 'E zigara nkwenye', view_verification: 'Lee ọnọdụ nkwenye', verification_rejected: 'Ajụrụ nkwenye', pay_property_details: 'Kwụọ ụgwọ maka nkọwa ụlọ', browse_properties: 'Chọgharịa ụlọ', withdrawal_notice: 'Iwepụ ego ịkwụ ụgwọ ụlọ', registration_prefill: 'Ejuola ebe ndebanye aha gị iji dozie nchọta ndị bi n’ụlọ na mbipụta onye nwe ụlọ. Ị ka nwere ike ịgbanwe ya.', assigned_landlord_notice: 'Ị na-agbakwunye ụlọ a n’aha onye nwe ụlọ e kenyere gị.' },
};

export default Object.fromEntries(Object.entries(copy).map(([locale, values]) => [locale, { dashboardUx: { ...values, ...resultCopy[locale], ...negotiationCopy[locale], ...destinationStatusCopy[locale] } }]));
